### ISSUE TITLE
Print requests to stdout

### ISSUE THREAD

**Issue by pataquets** [traefik/whoami#30]
Useful for testing container logging

**Comment by antgubarev** [comment]
https://github.com/traefik/whoami/pull/42 pls review my PR

**Comment by dennisstritzke** [comment]
Is there any interest to include this feature in whoami? It would be great to get some request info on the server side.

If this is a feature you would like to see in whoami, what would a PR need to be merged? Is #42 ok? Do we need an alternative using `log.Println` or `fmt.Println`?

**Comment by antgubarev** [comment]
https://github.com/traefik/whoami/pull/42#issuecomment-920803295 :(

**Comment by kevinpollet** [comment]
Closed by #50
