### ISSUE TITLE
Newer docker image

### ISSUE THREAD

**Issue by 030** [traefik/whoami#45]
It seems that the latest docker image does not contain the WHOAMI_PORT env feature. Could a newer docker image be created?

**Comment by 030** [comment]
@ldez Would it be possible to setup github actions in this repository? If a tag is set then the github action could build an image and subsequently push it to dockerhub.

**Comment by ldez** [comment]
the GHactions is already set https://github.com/traefik/whoami/tree/master/.github/workflows

**Comment by 030** [comment]
Ok thank you.
