### ISSUE TITLE
Images not being pushed to docker hub

### ISSUE THREAD

**Issue by adyanth** [traefik/whoami#48]
The last update on docker hub seems to be 2 years ago. The GitHub actions seems to skip over the docker hub image push. 

Context: I need the WHOAMI_PORT_NUMBER to be set, but the latest image on docker hub does not support that.

**Comment by ldez** [comment]
Hello,

the image is available on the Docker Hub https://hub.docker.com/repository/docker/traefik/whoami

The images are pushed to Docker Hub when a tag is created.

**Comment by adyanth** [comment]
Ahh, looks like I missed that piece of info. Thanks so much!
