### ISSUE TITLE
Reconsider app binary name

### ISSUE THREAD

**Issue by yermulnik** [traefik/whoami#53]
Could this please be considered to rename the app binary to not overlap with a common *NIX tool `whoami` (`man 1 whoami`) so that those who prefer to not use Docker but install binary directly with `go install` (or by other means, e.g. Homebrew) don't suffer from a need to apply local quirks for this app to not overlap with `whoami` from base *NIX distros.
Thank you in advance.

**Comment by ldez** [comment]
whoami has been built to be used inside the tests of Traefik and with containers.

The target was not to create a tool to be used outside of Traefik's context.

So we will not change the name.

**Comment by yermulnik** [comment]
Got you. Thanks.

> The target was not to create a tool to be used outside of Traefik's context.

Would have worthen of mentioning in README though to eliminate confusion for passer-by's like me 😺

**Comment by ldez** [comment]
Note: if you want to change the name, you can do it by changing the value of the flag `-o`:

https://github.com/traefik/whoami/blob/87f25fc35b3e9051117dddfd11bbae5fbc986581/Makefile#L8

ex:
```bash
 CGO_ENABLED=0 go build -a --trimpath --installsuffix cgo --ldflags="-s" -o traefik-whoami
```

**Comment by ldez** [comment]
Note: it's not because it was built for Traefik's testing that you cannot use it outside of this context but because we don't plan to create the "ultimate whoami application" :smile:. So the name or the features should not impact our main goal.

**Comment by yermulnik** [comment]
> Note: if you want to change the name, you can do it by changing the value of the flag `-o`:

Thanks for the pointer.

> we don't plan to create the "ultimate whoami application" 😄

Though you made it to pick up common unixish util name 😄
