### ISSUE TITLE
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by rishta** [traefik/whoami#61]
Trying on ARM64, _Linux odroid 5.4.196-406 #1 SMP PREEMPT Tue May 31 19:52:19 UTC 2022 armv7l armv7l armv7l GNU/Linux_

**Comment by ldez** [comment]
Hello,

There are only entries for arm64 and amd64.

armv7 is not arm64.

**Comment by ldez** [comment]
I added armv7: https://hub.docker.com/r/traefik/whoami/tags
