### ISSUE TITLE
Publish to ghcr.io as well as dockerhub

### ISSUE THREAD

**Issue by ColdHeat** [traefik/whoami#65]
Hello! Thanks for maintaining this server, it's a really useful testing tool! Is there any chance that the image could be published to ghcr.io (Github Packages) as well as Dockerhub? Would a PR be accepted for this?

**Comment by ldez** [comment]
Hello,

we don't plan to do that, whoami is just a small testing tool, our image is published in the Docker Hub.
The Docker Hub has limitations, those limitations are large enough for personal usage.

**Comment by ColdHeat** [comment]
Hi there, with the recent announcements by Docker would you be willing to reconsider this issue?

https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf
https://blog.alexellis.io/docker-is-deleting-open-source-images/
