### ISSUE TITLE
Cleanup the containous/whoami vs traefik/whoami

### ISSUE THREAD

**Issue by shalak** [traefik/whoami#67]
There's a little mess with the image on Docker hub:
- https://hub.docker.com/r/containous/whoami mentions https://www.github.com/containous/whoami as source repository, which redirects to https://github.com/traefik/whoami
- `containous/whoami` contains old image, without features mentioned on https://github.com/traefik/whoami

**Comment by ldez** [comment]
Hello,

There is no mess here, we moved the project from `containous` GitHub org to `traefik` GitHub org.

The image `containous/whoami` is not maintained. This image is here for compatibility reasons (avoid breaking people that use this image).

**Comment by shalak** [comment]
I see. Maybe it's a good idea to mention this on https://hub.docker.com/r/containous/whoami page?

**Comment by ldez** [comment]
This page cannot be edited: Docker uses readme information, but this readme is now gone since the migration.
