### ISSUE TITLE
Add X-Forwarded-For to access log

### ISSUE THREAD

**Issue by shalak** [traefik/whoami#70]
When running `whoami` behind `traefik`, we cannot distinguish from access log which host has made a request to it - they all come from traefik. Adding the `X-Forwarded-For` or `X-Real-IP` would be a great addition.

**Comment by ldez** [comment]
`whoami` already display all headers.

**Comment by shalak** [comment]
But not in access log - it returns the headers to client, and client may not have any output capabilities.

**Comment by ldez** [comment]
`whoami` doesn't write access log.
