### ISSUE TITLE
whoami stops after 10 minutes

### ISSUE THREAD

**Issue by meyergru** [traefik/whoami#86]
Maybe I am just too dumb and after all, it is no biggie anyways:

My whoami instances always stop after ~10 minutes after start. I deploy whoami alongside traefik just to have a reference. I know I can have it restart automatically, but I had expected it to run forever.

I can see nothing in the documentation or the code that beats me to why this happens or is that a "works as designed" thing?

There are no log errors after the initial start message, the exit code is 255.

**Comment by ldez** [comment]
Hello,

`whoami` can be run forever, there are no existing limitations.

Maybe it's related to your orchestrator that killed the container.
I think you should investigate in this direction.

**Comment by meyergru** [comment]
My bad:

I wrongly assumed that another service using "depends_on" in a docker compose file pulls in the underlying service, while in reality it only determines the start order. Thus, if the whole docker host is restarted and a service lacks a "restart" clause, it will not be restarted along with the main service which has such a clause.

Sorry for the noise.
